language: swift
osx_image: xcode9
before_install:
- brew update
- brew install carthage || brew outdated carthage || brew upgrade carthage
branches:
  only:
    - master
script:
  - set -o pipefail && xcodebuild build test -project HamsterUIKit.xcodeproj -scheme HamsterUIKit -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.3.1' | xcpretty --color
